# whitelisted branches
branches:
  only:
    - docs
    
language: node_js

node_js:
  - "node"

install: 
  - pip install mkdocs
  - npm install --global surge

script: 
  - mkdocs build --clean

after_success: 
  - "$TRAVIS_PULL_REQUEST == 'false' && surge --project ./site --domain alasql.surge.sh"

