# whitelisted branches
branches:
  only:
    - docs
    
language: python

python:
  - "2.7"
  
install: 
  - pip install mkdocs
  - pip install markdown-include
  - npm install -g surge

script: echo Go!

after_success: 
  - $TRAVIS_PULL_REQUEST == 'false'
  - rm -fr ./docs/wiki 
  - git --git-dir=/dev/null clone --depth 1 https://github.com/agershun/alasql.wiki ./docs/wiki 
  - mkdocs build --clean 
  - surge ./site/
