# whitelisted branches
branches:
  only:
    - docs
    
language: python

python:
  - "2"
  
install: 
  - pip install mkdocs
  - npm install -g surge

script: 
  - mkdocs build --clean

after_success: 
  - "$TRAVIS_PULL_REQUEST == 'false' && surge --project ./site --domain alasql.surge.sh"

