# whitelisted branches
branches:
  only:
    - docs
    
language: python

python:
  - "2.7"
  
install: 
  - npm run install

script: 
  - npm run get-wiki
  - npm run build


after_success:   
  - echo $TRAVIS_PULL_REQUEST == 'false' 
  - npm run publish 
