# whitelisted branches
branches:
  only:
    - docs
    
language: python

python:
  - "2.7"
  
install: 
  - pip install mkdocs
  - pip install markdown-include
  - npm install -g surge

script: 
  - echo Go!

after_success: 
  - "$TRAVIS_PULL_REQUEST == 'false' && npm run deploy"
