# whitelisted branches
branches:
  only:
    - docs
    
language: python

python:
  - "2.7"
  
install: 
  - npm run install

script: 
  - npm run get-wiki
  - npm run build

deploy:
  skip_cleanup: true

after_deploy:
  -  npm run publish 
